baseurl: "/essai-webpage/"
permalink: pretty
title: 'EssAI'

google_analytics_id: ""

homepage:
  show_call_box: true

logo:
  mobile: "images/logo/logo_essai.svg"
  desktop: "images/logo/logo_essai.svg"
  desktop_height: "36px"

footer:
  copyright_text: 'Free Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

seo:
  meta_og_title: "EssAI"
  meta_og_type: "website"
  meta_og_url: "http://essai-writing.site/"
  meta_og_image: "https://github.com/Stanley-Ye/essai-webpage/raw/master/images/logo/logo.png"
  meta_og_description: "EssAI is a ML-driven writing style trainer."

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
